// const myNumbers = [1,2,3,4,5,6,7,8,9,10]

// const newnums = myNumbers.map((num)=>num+10)
// console.log(newnums);

// -------------------------Chaining-------------------------

const myNumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

const newnums = myNumbers
                .map((num) => num * 10)   //value or new array generated by this method will pass on into the next method of the chain
                .map((num) => num+1)      // this method will perform actions on the received value of array from the previous method
                .filter((num) => num>30);
console.log(newnums);
